/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.exemplocreate;

import static com.mycompany.exemplocreate.TelaInsert.conecta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0022216
 */
public class TelaSelectAtividade extends javax.swing.JInternalFrame {
    Object clicou;
    /**
     * Creates new form TelaSelect
     */
    public TelaSelectAtividade() {
        initComponents();
    }
    
    public static int total(){
        String sql = "SELECT * FROM veiculos";
        Connection c = TelaInsert.conecta();
        int total = 0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                total++;
                System.out.println(
                        rs.getString("modelo")
                );
            }
            
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        } 
        return total;
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMontaTabela = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnMontaTabela1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnMontaTabela.setText("Monta Tabela");
        btnMontaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontaTabelaActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMontaTabela1.setText("Monta Tabela");
        btnMontaTabela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontaTabela1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnMontaTabela)
                        .addGap(63, 63, 63)
                        .addComponent(btnMontaTabela1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMontaTabela)
                    .addComponent(btnMontaTabela1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeletar)
                        .addGap(106, 106, 106)
                        .addComponent(jButton1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMontaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontaTabelaActionPerformed
        // TODO add your handling code here:
        int total = total();
        Object[] col = new Object[3];
        col[0]="Id";
        col[1]="Modelo";
        col[2]="Ano";
        Object[][] lin = new Object[total][3];
        String sql = "SELECT * FROM veiculos";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("id");
                lin[cont][1]=rs.getString("modelo");
                lin[cont][2]=rs.getInt("ano_fabricacao");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnMontaTabelaActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(
                this, 
                "Tem certeza");
        if(op==0){
            String comando = "DELETE FROM veiculos WHERE id=?";
            int id = Integer.valueOf((String) clicou);
            try {
                Connection c = conecta();
                PreparedStatement stmt = c.prepareStatement(comando);
                stmt.setInt(1, id);
                stmt.executeUpdate();
                btnMontaTabela.doClick();
            } catch (Exception e) {
                System.out.println("Erro "+e.getMessage());
            }
        }
       
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        clicou = jTable1.getValueAt(
                jTable1.getSelectedRow(), 
                0);
        System.out.println("Clicou "+clicou);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM veiculos";
        Connection c = TelaInsert.conecta();
        int total = 0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                total++;
                System.out.println(
                        rs.getString("modelo")
                );
            }
            
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        } 
        
        
        
        Object[] col = new Object[3];
        col[0]="Id";
        col[1]="Modelo";
        col[2]="Ano";
        Object[][] lin = new Object[total][3];
        sql = "SELECT * FROM veiculos";
        c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("id");
                lin[cont][1]=rs.getString("modelo");
                lin[cont][2]=rs.getInt("ano_fabricacao");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void btnMontaTabela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontaTabela1ActionPerformed
        // TODO add your handling code here:
        int total = total();
        Object[] col = new Object[4];
        col[0]="Id";
        col[1]="Modelo";
        col[2]="Ano";
        col[3]="Marca";
        Object[][] lin = new Object[total][4];
        String sql = "SELECT * FROM veiculos INNER JOIN marcas ON veiculos.marca_id = marcas.id";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("id");
                lin[cont][1]=rs.getString("modelo");
                lin[cont][2]=rs.getInt("ano_fabricacao");
                lin[cont][3]=rs.getString("descricao");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnMontaTabela1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnMontaTabela;
    private javax.swing.JButton btnMontaTabela1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
