/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.exemplocreate;

import static com.mycompany.exemplocreate.TelaInsert.conecta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author 0022216
 */
public class TelaTabelasDados extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTabelasDados
     */
    public TelaTabelasDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Criar Tabela users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Criar Tabela history");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Inserir 3 users");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Inserir 5 históricos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Apagar Tabela users");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Apagar Tabela history");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Inserir 3 users sem TRANSAÇÃO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 204, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Inserir 3 users com TRANSAÇÃO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton8))
                .addGap(44, 44, 44)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "CREATE table if not exists users("
                    +"id serial PRIMARY KEY,"
                    + "username varchar(30),"
                    + "password varchar(20),"
                    + "quant INTEGER)";
            Statement stmt = c.createStatement();
            stmt.execute(comando);
            c.close();
            JOptionPane.showMessageDialog(this, "Tabela Criada");
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "DROP table users";
            Statement stmt = c.createStatement();
            stmt.execute(comando);
            c.close();
            JOptionPane.showMessageDialog(this, "Tabela Apagada");
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "INSERT INTO users ("
                    + "username,"
                    + "password,"
                    + "quant) "
                    + "VALUES ("
                    + "?,"
                    + "?,"
                    + "?)";
            PreparedStatement stmt;
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "user01");
            stmt.setString(2, "123456");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "neo");
            stmt.setString(2, "abc");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "morpheu");
            stmt.setString(2, "xxx");
            stmt.setInt(3, 3);
            stmt.execute();
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "CREATE table if not exists history ("
            +"id serial PRIMARY KEY,"
            + "id_user INTEGER,"
            + "dataHora TIMESTAMP,"
            + "success INTEGER) " ;
            Statement stmt = c.createStatement(); 
            stmt.execute(comando);
            c.close();
            JOptionPane. showMessageDialog (this,"Tabela Criada");
        }
        catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            LocalDateTime quando = LocalDateTime.now();
            Timestamp timestamp = Timestamp.valueOf (quando) ;

            Connection c;
            c = conecta () ;

            String comando = "INSERT INTO history ("
                + "id_user,"
                + "dataHora,"
                + "success) "
                + "VALUES (?,?,?)";
                PreparedStatement stmt;
                stmt = c. prepareStatement(comando) ;
                stmt.setInt(1, 1) ;
                stmt.setTimestamp(2, timestamp);
                stmt.setInt(3, 1) ;
                stmt. execute() ;
                
                stmt.setInt(1, 2) ;
                stmt.setTimestamp(2, timestamp);
                stmt.setInt(3, 1) ;
                stmt. execute() ;
                
                stmt.setInt(1, 3) ;
                stmt.setTimestamp(2, timestamp);
                stmt.setInt(3, 1) ;
                stmt. execute() ;
                
                stmt.setInt(1, 2) ;
                stmt.setTimestamp(2, timestamp);
                stmt.setInt(3, 0) ;
                stmt. execute() ;
                
                stmt.setInt(1, 3) ;
                stmt.setTimestamp(2, timestamp);
                stmt.setInt(3, 0) ;
                stmt. execute() ;
                
                
        }catch (Exception e) {
            System.out.println("Erro "+e.getMessage ()) ;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "DROP table history";
            Statement stmt = c.createStatement();
            stmt.execute(comando);
            c.close();
            JOptionPane.showMessageDialog(this, "Tabela Apagada");
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = conecta();
            String comando = "INSERT INTO users ("
                    + "username,"
                    + "password,"
                    + "quant) "
                    + "VALUES ("
                    + "?,"
                    + "?,"
                    + "?)";
            PreparedStatement stmt;
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "user01");
            stmt.setString(2, "123456");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "neo");
            stmt.setString(2, "abc");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "morpheu");
            stmt.setString(2, "xxx");
            stmt.setInt(3, 3);
            stmt.setInt(4, 11111);
            stmt.execute();
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Connection c;
        c = conecta();
        try {         
            // Desabilita o autocommit para iniciar a transação manualmente
            c.setAutoCommit(false);
    
            String comando = "INSERT INTO users ("
                    + "username,"
                    + "password,"
                    + "quant) "
                    + "VALUES ("
                    + "?,"
                    + "?,"
                    + "?)";
            PreparedStatement stmt;
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "user01");
            stmt.setString(2, "123456");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "neo");
            stmt.setString(2, "abc");
            stmt.setInt(3, 0);
            stmt.execute();
            
            stmt = c.prepareStatement(comando);
            stmt.setString(1, "morpheu");
            stmt.setString(2, "xxx");
            stmt.setInt(3, 3);
            stmt.setInt(4, 11111);
            stmt.execute();
            
            // Confirma a transação
            c.commit();
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
            try {
                if (c != null) {
                    c.rollback();
                }
            } catch (SQLException se) {
                System.out.println("Erro no rollback: " + se.getMessage());
            }
        }finally {
            try {
                // Restaura o autocommit para o comportamento padrão
                if (c != null) {
                    c.setAutoCommit(true);
                }
            } catch (SQLException se) {
                System.out.println("Erro ao restaurar autocommit: " + se.getMessage());
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
