/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.exemplocreate;

import static com.mycompany.exemplocreate.TelaInsert.conecta;
import static com.mycompany.exemplocreate.TelaSelectAtividade.total;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0022216
 */
public class TelaHistorico extends javax.swing.JInternalFrame {

     public static int totalUsers(){
        String sql = "SELECT * FROM users";
        Connection c = TelaInsert.conecta();
        int total = 0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                total++;
                System.out.println(
                        rs.getString("username")
                );
            }
            
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        } 
        return total;
    }
     
     public static int totalUsersJoin(int quant){
        String sql = "SELECT * FROM users INNER JOIN  history on users.id=history.id_user WHERE quant>="+quant;
        Connection c = TelaInsert.conecta();
        int total = 0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                total++;
                System.out.println(
                        rs.getString("username")
                );
            }
            
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        } 
        return total;
    }
     
     
     
    /**
     * Creates new form TelaHistorico
     */
    public TelaHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListaUsuarios = new javax.swing.JButton();
        btnListaHistoricos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnListaBloquados = new javax.swing.JButton();
        btnDesbloquear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        btnListaUsuarios.setBackground(new java.awt.Color(0, 204, 255));
        btnListaUsuarios.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnListaUsuarios.setText("Lista Usuários");
        btnListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaUsuarios);
        btnListaUsuarios.setBounds(10, 20, 150, 30);

        btnListaHistoricos.setBackground(new java.awt.Color(153, 255, 153));
        btnListaHistoricos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListaHistoricos.setText("Lista Históricos");
        btnListaHistoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaHistoricosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaHistoricos);
        btnListaHistoricos.setBounds(170, 20, 150, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Data/Hora", "Success"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 620, 285);

        btnListaBloquados.setBackground(new java.awt.Color(255, 255, 204));
        btnListaBloquados.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListaBloquados.setText("Lista Bloqueados");
        btnListaBloquados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaBloquadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaBloquados);
        btnListaBloquados.setBounds(330, 20, 150, 30);

        btnDesbloquear.setBackground(new java.awt.Color(204, 204, 204));
        btnDesbloquear.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDesbloquear.setText("Desbloquear");
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesbloquear);
        btnDesbloquear.setBounds(490, 20, 150, 30);

        setBounds(0, 0, 677, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUsuariosActionPerformed
        // TODO add your handling code here:
        int total = totalUsers();
        Object[] col = new Object[4];
        col[1]="Username";
        col[2]="Password";
        col[0]="Id";
        col[3]="Quant";
        Object[][] lin = new Object[total][4];
        String sql = "SELECT * FROM users";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getInt("id");
                lin[cont][1]=rs.getString("username");
                lin[cont][2]=rs.getString("password");
                lin[cont][3]=rs.getInt("quant");
                cont++;
            }
            
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnListaUsuariosActionPerformed

    private void btnListaHistoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaHistoricosActionPerformed
        // TODO add your handling code here:
        int total = totalUsersJoin(0);
        Object[] col = new Object[4];
        col[0]="Username";
        col[1]="Password";
        col[2]="Data/Hora";
        col[3]="Success";
        Object[][] lin = new Object[total][4];
        String sql = "SELECT * FROM users INNER JOIN  history on users.id=history.id_user";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("username");
                lin[cont][1]=rs.getString("password");
                lin[cont][2]=rs.getString("dataHora");
                lin[cont][3]=rs.getString("success");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnListaHistoricosActionPerformed

    private void btnListaBloquadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaBloquadosActionPerformed
        // TODO add your handling code here:
        int total = totalUsersJoin(0);
        Object[] col = new Object[4];
        col[0]="Username";
        col[1]="Password";
        col[2]="Quant";
        Object[][] lin = new Object[total][4];
        String sql = "SELECT * FROM users WHERE quant>=3";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("username");
                lin[cont][1]=rs.getString("password");
                lin[cont][2]=rs.getString("quant");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnListaBloquadosActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE users set "
                + "quant=? "
                + "WHERE username=?";
        try {
            Connection c = conecta();
            PreparedStatement stmt = c.prepareStatement(sql);
            String username = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
            
            System.out.println("un "+username);
            stmt.setInt(1, 0);
            stmt.setString(2, username);
            
            System.out.println("stmt "+stmt);
           
            stmt.executeUpdate();
            btnListaBloquados.doClick();
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_btnDesbloquearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnListaBloquados;
    private javax.swing.JButton btnListaHistoricos;
    private javax.swing.JButton btnListaUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
