/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.exemplocreate;

import static com.mycompany.exemplocreate.TelaHistorico.totalUsers;
import static com.mycompany.exemplocreate.TelaInsert.conecta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0022216
 */
public class TelaLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdPass_1 = new javax.swing.JPasswordField();
        btnOk_1 = new javax.swing.JButton();
        btnCancelar_1 = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Login com Histórico");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(42, 28, 339, 48);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Usuário");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 100, 30);

        txtUser_1.setText("morpheu");
        getContentPane().add(txtUser_1);
        txtUser_1.setBounds(168, 120, 120, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 30);

        pwdPass_1.setText("xxx");
        getContentPane().add(pwdPass_1);
        pwdPass_1.setBounds(168, 160, 120, 30);

        btnOk_1.setBackground(new java.awt.Color(0, 204, 255));
        btnOk_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOk_1.setForeground(new java.awt.Color(255, 255, 255));
        btnOk_1.setText("Ok");
        btnOk_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk_1);
        btnOk_1.setBounds(114, 221, 72, 30);

        btnCancelar_1.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar_1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar_1.setText("Cancelar");
        btnCancelar_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar_1);
        btnCancelar_1.setBounds(204, 221, 77, 30);

        btnOk.setBackground(new java.awt.Color(255, 255, 204));
        btnOk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOk.setForeground(new java.awt.Color(102, 102, 102));
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(20, 213, 72, 40);

        setBounds(0, 0, 462, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOk_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk_1ActionPerformed
        String user = txtUser_1.getText();
        String userSecreto = "user";
        char[] senha = pwdPass_1.getPassword();
        char[] senhaSecreta = {'e','3','r','4','T','%','y','6'};

        int result;
        result = Arrays.compare(senha,senhaSecreta);

        if( (user.equals(userSecreto)) && (result==0) ){
            this.dispose();
            TelaBemVindo tela = new TelaBemVindo();
            Tela.area.add(tela);
            tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                this,
                "Verifique seu usuário e senha",
                "Titulo",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOk_1ActionPerformed

    private void btnCancelar_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_1ActionPerformed
        // TODO add your handling code here:
        txtUser_1.setText("");
        pwdPass_1.setText("");
    }//GEN-LAST:event_btnCancelar_1ActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //variáveis que vamos usar
        Operacao operacao = new Operacao();
        char[] senhaBanco;
        String user = txtUser_1.getText();
        char[] pass = pwdPass_1.getPassword(); 
        User u = operacao.buscaUser(user);
        //vamos converter a senha do banco em char[]
        senhaBanco = operacao.converteStringToChar(u.getPassword());
        if(u.getUsername().equals(user)){
            if(Arrays.equals(senhaBanco,pass)){
                if(u.getQuant()<=3){
                    System.out.println("LOGOU");
                    TelaBemVindo t = new TelaBemVindo();
                    Tela.area.add(t);
                    t.setVisible(true);
                    this.dispose();
                    //vamos gravar o histórico de Sucesso!!
                    operacao.historico(u.getId(), 1);
                    //acertou tudo então bora registrar que deu certo
                    operacao.atualizaQuant(u.getId(), 0);    
                }else{
                    //conta bloqueada
                    JOptionPane.showMessageDialog(this, "Conta Bloqueada");
                }
            }else{
                //vamos gravar o histórico de Erro!!
                operacao.historico(u.getId(), 0);
                //errou a senha então bora registrar este erro no contado de erro da conta deste user
                operacao.atualizaQuant(u.getId(), u.getQuant());
                JOptionPane.showMessageDialog(this, "senha incorreta");
            }
        }else{
            System.out.println("Errouuuuuuuuu");
        }     
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar_1;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOk_1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwdPass_1;
    private javax.swing.JTextField txtUser_1;
    // End of variables declaration//GEN-END:variables
}
