/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.exemplocreate;

import static com.mycompany.exemplocreate.TelaInsert.conecta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0022216
 */
public class TelaSelect extends javax.swing.JInternalFrame {
    Object clicou;
    /**
     * Creates new form TelaSelect
     */
    public TelaSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnMontaTabela = new javax.swing.JButton();
        btnLimpaTabela = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnSalvarAlteracoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtQuilometragem = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 381, 235);

        jButton1.setText("Exemplo 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 220, 85, 23);

        jButton2.setText("Exemplo FOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 220, 101, 23);

        jButton3.setText("A a");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 220, 72, 23);

        jButton4.setText("SELECT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 220, 87, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 250, 87, 22);

        btnMontaTabela.setText("Monta Tabela");
        btnMontaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontaTabelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMontaTabela);
        btnMontaTabela.setBounds(450, 220, 102, 23);

        btnLimpaTabela.setText("Limpar tabela do banco");
        btnLimpaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaTabelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpaTabela);
        btnLimpaTabela.setBounds(420, 290, 155, 23);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(420, 350, 155, 23);

        btnSalvarAlteracoes.setText("Salvar alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(420, 400, 155, 23);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Modelo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 100, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ano");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 100, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Quilometragem");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 100, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 100, 30);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Marca");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 100, 30);
        getContentPane().add(txtModelo);
        txtModelo.setBounds(140, 10, 150, 30);
        getContentPane().add(txtAno);
        txtAno.setBounds(140, 50, 150, 30);
        getContentPane().add(txtQuilometragem);
        txtQuilometragem.setBounds(140, 90, 150, 30);
        getContentPane().add(txtValor);
        txtValor.setBounds(140, 130, 150, 30);
        getContentPane().add(txtMarca);
        txtMarca.setBounds(140, 170, 150, 30);

        setBounds(0, 0, 911, 569);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object[] col;
        col = new Object[2];
        col[0] = "Nome";
        col[1] = "Idade";
        
        Object[][] lin;
        lin = new Object[3][2];
        lin[0][0] = "João";
        lin[0][1] = 16;
        
        lin[1][0] = "Leo";
        lin[1][1] = 18;
        
        lin[2][0] = "Leo P";
        lin[2][1] = 15;
        
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object[] col = new Object[1];
        col[0]="Letra";
        Object[][] lin = new Object[26][1];
        for (int i = 0; i < 26; i++) {
            lin[i][0]=(char) (i+65);
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[] col = new Object[2];
        col[0]="LETRA";
        col[1]="letra";
        Object[][] lin = new Object[26][2];
        for (int i = 0; i < 26; i++) {
            lin[i][0]=(char) (i+65);
            lin[i][1]=(char) (i+97);
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM veiculos";
        Connection c = TelaInsert.conecta();
        int total = 0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                total++;
                System.out.println(
                        rs.getString("modelo")
                );
            }
            jTextField1.setText(String.valueOf(total));
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMontaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontaTabelaActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(jTextField1.getText());
        Object[] col = new Object[3];
        col[0]="Id";
        col[1]="Modelo";
        col[2]="Ano";
        Object[][] lin = new Object[total][3];
        String sql = "SELECT * FROM veiculos";
        Connection c = TelaInsert.conecta();
        int cont=0;
        try {
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                lin[cont][0]=rs.getString("id");
                lin[cont][1]=rs.getString("modelo");
                lin[cont][2]=rs.getInt("ano_fabricacao");
                cont++;
            }
        } catch (SQLException e) {
            System.out.println("Erro "+e.getMessage());
        }
        DefaultTableModel t;
        t = new DefaultTableModel(lin, col);
        jTable1.setModel(t);
    }//GEN-LAST:event_btnMontaTabelaActionPerformed

    private void btnLimpaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaTabelaActionPerformed
        // TODO add your handling code here:
        try {
            Connection c = conecta();
            String comando;
            comando="TRUNCATE TABLE veiculos  ";
            PreparedStatement stmt;
            stmt = c.prepareStatement(comando);
            stmt.executeUpdate();
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_btnLimpaTabelaActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        String comando = "DELETE FROM veiculos WHERE id=?";
        int id = Integer.valueOf((String) clicou);
        try {
            Connection c = conecta();
            PreparedStatement stmt = c.prepareStatement(comando);
            stmt.setInt(1, id);
            stmt.executeUpdate();
            btnMontaTabela.doClick();
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        clicou = jTable1.getValueAt(
                jTable1.getSelectedRow(), 
                0);
        System.out.println("Clicou "+clicou);
        String sql = "SELECT * FROM veiculos WHERE id=?";
        Connection c = conecta();
        try {
            PreparedStatement stmt = c.prepareStatement(sql);
            int id = Integer.valueOf((String) clicou);
            stmt.setInt(1, id);
            ResultSet result = stmt.executeQuery();
            result.next();
            String modelo = result.getString("modelo");
            txtModelo.setText(modelo);
            
            Integer marca = result.getInt("marca_id");
            txtMarca.setText(String.valueOf(marca));
           
            Integer quilometragem = result.getInt("quilometragem");
            txtQuilometragem.setText(String.valueOf(quilometragem));
            
            Integer ano = result.getInt("ano_fabricacao");
            txtAno.setText(String.valueOf(ano));
            
            Double valor = result.getDouble("valor");
            txtValor.setText(String.valueOf(valor));
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE veiculos set "
                + "modelo=?,"
                + "ano_fabricacao=?,"
                + "quilometragem=?,"
                + "valor=?,"
                + "marca_id=? "
                + "WHERE id=?";
        try {
            Connection c = conecta();
            PreparedStatement stmt = c.prepareStatement(sql);
            String modelo = txtModelo.getText();
            stmt.setString(1, modelo);
            
            Integer ano =Integer.valueOf(txtAno.getText());
            stmt.setInt(2, ano);
            
            Integer quilometragem =Integer.valueOf(txtQuilometragem.getText());
            stmt.setInt(3, quilometragem);
            
            Double valor = Double.valueOf(txtValor.getText());
            stmt.setDouble(4, valor);
            
            Integer marca =Integer.valueOf(txtMarca.getText());
            stmt.setInt(5, marca);
            
            int idClicado = Integer.parseInt((String)clicou);
            stmt.setInt(6, idClicado);
            stmt.executeUpdate();
            btnMontaTabela.doClick();
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpaTabela;
    private javax.swing.JButton btnMontaTabela;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtQuilometragem;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
